### ISSUE TITLE
64bit builder issue - create_linux_vault_package.sh 

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/QA#14]
Currently seeing this issue when running `create_linux_vault_package.sh`
```
/usr/local/bin/fpm:9:in `require': no such file to load -- rubygems (LoadError)
	from /usr/local/bin/fpm:9
```

I am investigating it looks like an environment issue

**Comment by dirvine** [comment]
looks like a ruby dependency that is missing. Possibly because fpm is in /local/

**Comment by Fraser999** [comment]
Where are you running this - on your own machine?

**Comment by rossmuir** [comment]
Cool David thanks yeah I am just uninstalling and reinstalling fpm and the dependencies :-)
@Fraser no Builder-64-bit

**Comment by rossmuir** [comment]
Hi Fraser - I removed all the ruby / gem installs from the builder that had been installed manually under the `Fraser` user and installed via `apt-get` as per the instructions in the create package script this fixed the ruby errors, however `apt-get` installs an older version of which is too old for fpm (it wants > 2.0.x) a patch is available here (not yet merged)
https://github.com/jordansissel/fpm/commit/02df699ff9c84a83ed879f89d81896cbe954f667 
I guess this is why you manually installed it all before - I shall manually install everything under the `maidsafe` user

**Comment by rossmuir** [comment]
Used > https://www.digitalocean.com/community/tutorials/how-to-install-ruby-2-1-0-and-sinatra-on-ubuntu-13-with-rvm
and
http://stackoverflow.com/questions/9056008/installed-ruby-1-9-3-with-rvm-but-command-line-doesnt-show-ruby-v/9056395#9056395

**Comment by fraser** [comment]
Hi - just noting I think you've got the wrong Fraser in your mention in https://github.com/maidsafe/QA/issues/14#issuecomment-151795816 :)

**Comment by rossmuir** [comment]
Sorry about that @fraser I did mean @Fraser999 - so thanks :-)

**Comment by fraser** [comment]
No problem!
