### ISSUE TITLE
how to access public link by another PC

### ISSUE THREAD

**Issue by cheershendtco** [maidsafe/QA#46]
![mwsnap011](https://cloud.githubusercontent.com/assets/21186623/18115381/9d71bd92-6f71-11e6-985c-fb997bd6e31d.jpg)

I can browse the file by my own PC. I use SAFE Demo App and SAFE Launcher.
but how can I browse by another PC
Thanks.

**Comment by krishnaIndia** [comment]
SAFE Launcher should be installed on the machine from where you intend to view the safe sites. 
- Install SAFE Launcher
- Start the SAFE Launcher
- Go to settings and ensure `Web Proxy` is enabled

Also, you will have to configure the proxy on that machine.

For launcher related issues, you can file it [safe_launcher repository](https://github.com/maidsafe/safe_launcher)
