### ISSUE TITLE
Rust: tests run with --release won't trigger debug assertions

### ISSUE THREAD

**Issue by Ryman** [maidsafe/QA#7]
There seems to be one commit which [tries to run them without `--release`](https://github.com/maidsafe/QA/commit/40cd52e524bf89ee12030d91a4640873a41d9804) but it's removed in a subsequent commit with [no commentary as to why](https://github.com/maidsafe/QA/commit/caff86e5f355482c0bddac3066950aafd8688f8e).

Debug assertions includes various safety checks including overflow checks so it's worth running, or using the explicit types such as [Wrapping&lt;T&gt;](http://doc.rust-lang.org/std/num/struct.Wrapping.html).

**Comment by Fraser999** [comment]
The debug runs were removed purely in an effort to reduce running times on Travis and AppVeyor.  

We were seeing large backlogs and timeouts, so opted to only run release tests on the basis that most developers are testing debug builds themselves and would encounter the debug assertions.
