### ISSUE TITLE
Improve Appveyor build times

### ISSUE THREAD

**Issue by Viv-Rajkumar** [maidsafe/QA#8]
Two features may be worth making active while currently limited to one concurrent job: 

- [Rolling builds](https://github.com/appveyor/ci/issues/38) - only builds the latest commit from a given PR(maybe branch wise too)
- Skip building github tags

both features are available from the settings UI for each project:

![screen shot 2015-09-17 at 16 01 23](https://cloud.githubusercontent.com/assets/841795/9936824/c342d846-5d55-11e5-9ec9-041c8d822c63.png)

**Comment by Fraser999** [comment]
Good points.  Neither of us have had time yet to properly explore the AppVeyor options open to us, but this at least is now done for every MaidSafe AppVeyor project.
